#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
# script should only display: username, user id, and Home directory path.
# must use the while loop.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
