#!/usr/bin/env bash
# script that displays Best School 10 times.
# but displays Hi on 9th position.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
