#!/usr/bin/env bash
# Bash script that displays:
# The content of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed 
# must use the for loop and not display hidden files.

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
